### ISSUE TITLE
The pre-trained weight file

### ISSUE THREAD

**Issue by helonin** [zhuqinfeng1999/Samba#1]
Hello, author! Thank you for publishing this effective research!
Could you share the pre-trained weight file?  Thx!

**Comment by zhuqinfeng1999** [comment]
Hello, thank you for your interest in our work!
Currently, our research does not utilize pre-trained models;  the specific training configurations are detailed within the paper, thus all comparative results are derived from training from scratch.  
However, our next steps involve testing our model across multiple datasets (already completed), followed by pre-training on ImageNet, which is upcoming.  Updates will be posted on GitHub and in our arXiv paper.
