### ISSUE TITLE
Code error:RuntimeError: stack expects each tensor to be equal size, but got [512, 512, 3] at entry 0 and [1, 512, 512] at entry 2

### ISSUE THREAD

**Issue by liuwenxin0410** [zhuqinfeng1999/Samba#4]
hello, When I run the following command: "bash tools/dist_train.sh configs/samba/samba_upernet-15k_loveda-512x512_6e4.py 2 --work-dir work_dirs/samba_upernet-15k_loveda-512x512_6e4 --amp".
The following error occurs :
RuntimeError: stack expects each tensor to be equal size, but got [512, 512, 3] at entry 0 and [1, 512, 512] at entry 2
seg_label = self._stack_batch_gt(batch_data_samples)
File "/data_sdc/liuTest/Samba/mmseg/models/decode_heads/decode_head.py", line 289, in _stack_batch_gt
return torch.stack(gt_semantic_segs, dim=0)
RuntimeError:  stack expects each tensor to be equal size, but got [1, 512, 512] at entry 0 and [409, 512, 106] at entry 2

**Comment by zhuqinfeng1999** [comment]
Hello! Thank you very much for your interest in our work.
This error occurs during the network's image input handling phase, and our dataloader is able to correctly load the LoveDA inputs. Could you please check if you have applied any additional cropping during data loading? Or if the LoveDA training and validation data you downloaded are correct?
Please feel free to contack us.

**Comment by xupinggl** [comment]
I trained with my own dataset and had the following problem:
![image](https://github.com/zhuqinfeng1999/Samba/assets/102807353/9afacda9-289d-44d7-89f0-18381569cdf2)
![image](https://github.com/zhuqinfeng1999/Samba/assets/102807353/9ce0877c-af50-4711-bd19-01a9e27d76ab)
