### ISSUE TITLE
What is the exact version of causal and mamba-ssm in the configuration?

### ISSUE THREAD

**Issue by StorywithLove** [zhuqinfeng1999/Samba#8]
Hello, what is the exact version of causal and mamba-ssm in the configuration? I tried several configurations and none of them work: (1) causal_conv1d_cuda.causal_conv1d_fwd()
TypeError: causal_conv1d_fwd(): function parameter incompatibility. The following parameter types are supported
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: optional [torch.Tensor], arg3: optional [torch.Tensor], arg4: bool) -> torch.)
(2) cuda error: no kernel image available

**Comment by StorywithLove** [comment]
And.
What are the versions of cuda and torch? I installed as per cuda 12.4, torch can only install the lightly version with 2.5, and subsequent causal-conv1d and mamba-ssm reported errors

**Comment by StorywithLove** [comment]
@zhuqinfeng1999

**Comment by zhuqinfeng1999** [comment]
![image](https://github.com/zhuqinfeng1999/Samba/assets/34743935/5e556cb8-fb14-4ebf-a9ba-a8388ba39df6)
Hi, my ubuntu system uses CUDA 12.4. And I use causal-conv1d==1.1.1, mamba-ssm==1.2.0.post1, pytorch==2.0.1.
Hope this will help.

**Comment by StorywithLove** [comment]
> ![image](https://private-user-images.githubusercontent.com/34743935/344970737-5e556cb8-fb14-4ebf-a9ba-a8388ba39df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzE5NTYsIm5iZiI6MTcyMDA3MTY1NiwicGF0aCI6Ii8zNDc0MzkzNS8zNDQ5NzA3MzctNWU1NTZjYjgtZmIxNC00ZWJmLWE5YmEtYTgzODhiYTM5ZGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA1NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNzczNWMzMjA3N2Q2N2FhOGZkNzI4NzlhODAwOTcyODlmZjc5Y2Y4NjBkYjdiMDYxYmIyMWNjMDMxMDE1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wDc0iTk_9H0A6WUwdcp0P0i0v977J5jvKF5Isik1lX0) Hi, my ubuntu system uses CUDA 12.4. And I use causal-conv1d==1.1.1, mamba-ssm==1.2.0.post1, pytorch==2.0.1. Hope this will help.

Thanks. Based on your response, I completed the environment build!!!
Here is my environment configuration and installation steps. 

Ubuntu 20.04 with P40 *3
Nvidia Driver 535, CUDA Version 12.2 (nvidia-smi)
ncc -V 11.8 (cudatoolkit )
sudo update-alternatives --config cuda (Select 11.8)

Torch, with pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
causal-conv1d, v1.2.0.post2, build with soure with CCC<7(https://github.com/state-spaces/mamba/issues/40#issuecomment-1849095898)
mamba-ssm, V1.2.0.post1, build with source like above.

mmcv, pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html
mmsg, pip install "mmsegmentation>=1.0.0”
